FROM node:12-alpine

ENV TZ='Asia/Tokyo'
#WORKDIR /app

#COPY ./app/package.json /app
#COPY ./app/package-lock.json /app
#RUN npm install

#COPY app /app

CMD [ "echo", "web server" ]
#CMD ["npm","start"]
