version: '3'
services:
  db:
    build: ./db_psql
    container_name: 'db_psql'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    volumes:
      - psql_data:/var/lib/postgresql/data

  api:
    tty: true
    build: ./backend
    container_name: 'api_rails'
    command: bundle exec rails s  -p 8080 -b '0.0.0.0'
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    tty: true
    build: ./frontend
    container_name: 'front_nuxt'
    command: npm run dev
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  psql_data:
  node_modules: