version: '3'
services:
  db:
    build: ./db_psql
    container_name: "db_psql"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    volumes:
      - psql_data:/var/lib/postgresql/data

  web:
    build: ./frontend
    container_name: "web_nuxt"
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - app

  app:
    build: ./backend
    container_name: "app_rails"
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  psql_data: