version: '3'
services:
  db:
    build: ./db_psql
    container_name: "db_psql"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    volumes:
      - psql_data:/var/lib/postgresql/data

  app:
    build: ./backend
    command: bundle exec rails s -p 8080 -b '0.0.0.0'
    container_name: "app_rails"
    volumes:
      - ./backend:/backend
    ports:
      - "8080:8080"
    depends_on:
      - db

  web:
    build: ./frontend
    command: npm run dev
    container_name: "web_nuxt"
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"
    depends_on:
      - app

volumes:
  psql_data: