blank_issues_enabled: false
contact_links:
  - name: BugReport
    url: https://github.com/NAKKA-K/musclers/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md
    about: Please report bug here.
  - name: FeatureRequest
    url: https://github.com/NAKKA-K/musclers/blob/develop/.github/ISSUE_TEMPLATE/feature_request.md
    about: Please request feature here.
