class LoggedinUserSerializer < ActiveModel::Serializer
  attributes(
    :id,
    :access_token,
    :nickname,
    :email,
    :thumbnail,
    :description,
    :age,
    :gender,
    :height,
    :weight,
    :figure,
    :muscle_mass,
    :body_fat_percentage,
    :seriousness,
    :created_at,
    :updated_at
  )
end
